import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Arimo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Arimo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      
      <body className='m-5 text-black uppercase'>
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
